### ISSUE TITLE
Complex array-valued Wiener process only produces real noise

### ISSUE THREAD

**Issue by danielwe** [SciML/DiffEqNoiseProcess.jl#101]
`WienerProcess(0.0, [0.0im])` only produces real-valued increments. MWE:

```julia
julia> using DiffEqNoiseProcess

julia> using DiffEqNoiseProcess: NoiseProblem, solve

julia> prob = NoiseProblem(WienerProcess(0.0, [0.0im]), (0.0, 1.0));

julia> sol = solve(prob; dt=0.1);

julia> sol.W[end]
1-element Vector{ComplexF64}:
 2.3820176552198165 + 0.0im
```

The scalar-valued equivalent produces complex noise as expected:

```julia
julia> prob = NoiseProblem(WienerProcess(0.0, 0.0im), (0.0, 1.0));

julia> sol = solve(prob; dt=0.1);

julia> sol.W[end]
-1.1828100925799103 + 1.4213457901396127im
```

---

Note that this doesn't seem to affect the default noise process for complex-valued SDEs in StochasticDiffEq. I'm just not able to manually instantiate a noise process that reproduces the default behavior:

```julia
julia> using StochasticDiffEq

julia> f!(du, u, p, t) = (du .= 0)
f! (generic function with 1 method)

julia> g!(du, u, p, t) = (du .= 1)
g! (generic function with 1 method)

julia> prob = SDEProblem(f!, g!, [0.0im], (0.0, 1.0));

julia> sol = solve(prob, EM(); dt=0.1);

julia> sol.u[end]
1-element Vector{ComplexF64}:
 -0.9054409033854848 - 0.4148766416920265im
```

**Comment by danielwe** [comment]
Oh, I see, the in-place `WienerProcess!` works. I'm confused: what's the difference between the two when initialized with an array?

**Comment by danielwe** [comment]
Looks like `WienerProcess` without the bang will eventually hit the following method, which fails to make use of the eltype `T` in the call to `randn`. That explains it.

https://github.com/SciML/DiffEqNoiseProcess.jl/blob/c3f3bb9bbb9b7cce41804f6847d0011f252daf2d/src/wiener.jl#L3-L5

**Comment by ChrisRackauckas** [comment]
Thanks for the investigation. Yeah this shows we should probably upgrade it to the new Base stuff.
