### ISSUE TITLE
`wiener_randn!` needs GPU-friendly fallback for complex AbstractArrays

### ISSUE THREAD

**Issue by danielwe** [SciML/DiffEqNoiseProcess.jl#102]
This method will process GPUArrays sequentially:

https://github.com/SciML/DiffEqNoiseProcess.jl/blob/c3f3bb9bbb9b7cce41804f6847d0011f252daf2d/src/wiener.jl#L18-L23

Should be tightened to `Array` and supplemented with a fallback, like in the real case.

However, looking at how the fallback for the real case works,

https://github.com/SciML/DiffEqNoiseProcess.jl/blob/c3f3bb9bbb9b7cce41804f6847d0011f252daf2d/src/wiener.jl#L15-L16

it's unfortunate that a custom rng will be ignored when working on GPU. CUDA.jl supports several RNG types at this point.

Then there's #6. Would it be better to rewrite this and get rid of `wiener_randn` altogether?

**Comment by ChrisRackauckas** [comment]
> Would it be better to rewrite this and get rid of wiener_randn altogether?

Yes. It can probably just be removed with modern Julia. We'd need to double check of course, but I'm 90% sure that would then clean it up and make it more robust. https://github.com/SciML/DiffEqNoiseProcess.jl/pull/103 adds the downstream tests that would make a merge of this change fairly safe.

**Comment by ChrisRackauckas** [comment]
Fixed by https://github.com/SciML/DiffEqNoiseProcess.jl/pull/157
