### ISSUE TITLE
`reinit!` not working properly with a `NoiseWrapper` noise

### ISSUE THREAD

**Issue by rmsrosa** [SciML/DiffEqNoiseProcess.jl#121]
As reported by a user on Slack, when solving twice an SDE with a noise of the type NoiseWrapper from a previous solve, the second solution differs from the previous solutions.

More specifically, when running the code at https://github.com/SciML/DiffEqNoiseProcess.jl/blob/eb57dded61255d48815c7c64d89fa5034f831cde/test/sde_noise_wrapper.jl up to line 14 and then running again lines 12 and 14, the solution is different.

**Comment by axsk** [comment]
Is it possible the same also happens for the VirtualBrownianTree? I think I just experienced the same behavior with that noise type.
