### ISSUE TITLE
VirtualBrownianTree cannot be reversed because it has no save_everystep field

### ISSUE THREAD

**Issue by glatteis** [SciML/DiffEqNoiseProcess.jl#152]
Hi all! I can't differentiate a `VirtualBrownianTree` using the `BacksolveAdjoint` because:

```
noise = VirtualBrownianTree(0f0, 0f0)
reverse(noise)
```

yields

```
ERROR: type VirtualBrownianTree has no field save_everystep
```

`BacksolveAdjoint` calls this method here: https://github.com/SciML/SciMLSensitivity.jl/blob/834a4c70c45c6525d66d6fa7ee7c29837435e0f9/src/backsolve_adjoint.jl#L332

**Comment by ChrisRackauckas** [comment]
@frankschae have you looked into this use case?

**Comment by glatteis** [comment]
I sent frank a message on slack :)

**Comment by glatteis** [comment]
Thanks so much! I'll try it out today :)

**Comment by glatteis** [comment]
Issue is fixed :)
