### ISSUE TITLE
Tutorial "Direct Simulation of the Noise Process]" is Broken

### ISSUE THREAD

**Issue by AlexanderNenninger** [SciML/DiffEqNoiseProcess.jl#165]
The example code ["Direct Simulation of the Noise Process"](https://docs.sciml.ai/DiffEqNoiseProcess/stable/#Direct-Simulation-of-the-Noise-Process) is broken. In Particular, the type `MonteCarloProblem` is not defined and I was not able to find a non-deprecated definition of `MonteCarloProblem` in the SciML ecosystem. Should this be changed to
```
using DifferentialEquations
using DiffEqNoiseProcess

W = GeometricBrownianMotionProcess(μ, σ, 0.0, S0)
prob = NoiseProblem(W, (0, T))
monte_prob = EnsembleProblem(prob)
sol = solve(monte_prob; dt=0.1, trajectories=100)
```
?

**Comment by ChrisRackauckas** [comment]
Thanks, fixed. We need to do a full pass on this package's documentation but that's at least good to have fixed for now.
