### ISSUE TITLE
Ornstein-Uhlenback Bridge distribution

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/DiffEqNoiseProcess.jl#2]
The bridge distribution needs to be implemented for this process in order for it to be used adaptively in RODEs and SDEs. But I don't know the distribution. Maybe @elevien knows?

**Comment by elevien** [comment]
What exactly do you need?

**Comment by ChrisRackauckas** [comment]
The Ornstein-Uhlenbeck Bridge. If `X(0)=X0`, `X(h)=Xh`, and `X(t)` is an Ornstein-Uhlenbeck process, i.e. 

```julia
dX(t) = Θ*(μ-X(t))*dt + σ*dW(t)
```

then what is the distribution of `X(q*h)` for `q∈[0,1]`? That would distribution is what's required to be able to interpolate the OU process.

**Comment by elevien** [comment]
https://arxiv.org/abs/1011.0067

I just skimmed this, but are the equations on page 18 helpful?

**Comment by ChrisRackauckas** [comment]
That looks great! Wonder why I couldn't find that.

**Comment by ChrisRackauckas** [comment]
@mschauer wrote it slightly differently, but the derivation looks good:

https://www.dropbox.com/s/odo7ur3u5aoph0l/ouremark.pdf?dl=0

I will change the internal OU to this form so that way the equations are clean like this. 

https://books.google.com/books?id=UYf_lHhL3sYC&pg=PA153&lpg=PA153&dq=Doss-Sussmann+transformation+RODE&source=bl&ots=56-kasbz1Z&sig=ezys5e8s2qrwjaI68iMN9F-wbnQ&hl=en&sa=X&ved=0ahUKEwjS1-v8z-XUAhUC5oMKHQA5CCkQ6AEIMTAD#v=onepage&q=Doss-Sussmann%20transformation%20RODE&f=false

5.24 and 5.25: this is the form that's needed for RODEs.

**Comment by mschauer** [comment]
I implemented the scalar case at https://github.com/mschauer/Bridge.jl/issues/15

**Comment by mschauer** [comment]
Is there still need for the multivariate Ornstein-Uhlenback Bridge distribution?

**Comment by ChrisRackauckas** [comment]
Yes, it's not a high priority but it would be useful for doing adaptive random ODE solvers

**Comment by Jonas-a-Zimmermann** [comment]
#161

**Comment by ChrisRackauckas** [comment]
Closed by https://github.com/SciML/DiffEqNoiseProcess.jl/pull/161
