### ISSUE TITLE
CorrelatedWienerProcess with adaptive timestep solvers?

### ISSUE THREAD

**Issue by oameye** [SciML/DiffEqNoiseProcess.jl#206]
**Question❓**

Can a ` CorrelatedWienerProcess` be used with adaptive timestep solvers? This code seems to suggest not?https://github.com/SciML/DiffEqNoiseProcess.jl/blob/a9d48fdcf67b7e0086a61bb47a99b16fa9b9bc8e/src/correlated_noisefunc.jl#L43-L45

**Comment by ChrisRackauckas** [comment]
It cannot be used without the bridging process.

However, you wouldn't really want to do it like this anyways. Instead, what you'd want to do is define the SDE that is equivalent to the correlation noise, and then use that SDE solution in the other sets and expand that system. That resulting system of SDEs is then equivalent to doing the correlated noise.
