### ISSUE TITLE
Filenames only differing by case makes the infrastructure confused.

### ISSUE THREAD

**Issue by KristofferC** [SciML/DiffEqNoiseProcess.jl#79]
This package contains both the files `CI.yml` and `ci.yml` in https://github.com/SciML/DiffEqNoiseProcess.jl/tree/master/.github/workflows. On case insenstivie systems, those will collapse into one file which means that the computed tree hash of the directory will depend on the file system. This causes https://github.com/JuliaLang/Pkg.jl/issues/2272.

It's best to name these file differently, ignoring case.

**Comment by ChrisRackauckas** [comment]
Having both was just a mistake introduced by a bot.
